global:
  scrape_interval: 30s
  external_labels:
    hydra_component: "hypercube"

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "node"
    static_configs:
      - targets: ["nodeexporter:9100"]

  - job_name: "ispmonitor"
    scrape_interval: 60s
    static_configs:
      - targets: ["100.94.241.54:9283"] # RPi telegraf Agent

  - job_name: "nomad_metrics"
    consul_sd_configs:
    - server: '{{ env "NOMAD_IP_prometheus_http" }}:8500'
      services: ['nomad-client', 'nomad']

    relabel_configs:
    - source_labels: ['__meta_consul_tags']
      regex: '(.*)http(.*)'
      action: keep

    scrape_interval: 5s
    metrics_path: /v1/metrics
    params:
      format: ['prometheus']
