version: "3.7"

services:
  caddy_public:
    image: mrkaran/caddy:2.2.1
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile_public:/etc/caddy/Caddyfile
      - /data/caddy_public:/data
    networks:
      - public

networks:
  public:
    name: caddy_public
